CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    status VARCHAR(255) DEFAULT 'NOT_AVAILABLE',
    seller BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE products
    ADD CONSTRAINT fk_product_seller
        FOREIGN KEY (seller)
            REFERENCES users(id);

ALTER TABLE products
    ADD COLUMN average_rating NUMERIC(3,2) DEFAULT 0.0,
    ADD COLUMN review_count BIGINT DEFAULT 0;

CREATE INDEX idx_products_average_rating ON products (average_rating DESC);

CREATE INDEX idx_products_review_count ON products (review_count DESC);

ALTER TABLE products
    ADD COLUMN quantity INT NOT NULL DEFAULT 0,
    ADD COLUMN reserved_quantity INT NOT NULL DEFAULT 0;

ALTER TABLE products
    ADD CONSTRAINT chk_reserved_quantity_non_negative
        CHECK (reserved_quantity >= 0);


ALTER TABLE products
    ADD CONSTRAINT chk_available_quantity_non_negative
        CHECK (quantity - reserved_quantity >= 0);
