CREATE TABLE users (
    id BIGINT PRIMARY KEY ,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL ,
    full_name VARCHAR(200) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP  NOT NULL DEFAULT NOW()
);